/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 iphone.glb --transform --draco 
Files: iphone.glb [583.71KB] > /Users/tianyuanbi/Downloads/3D Tim/public/assets/iphone-transformed.glb [137.84KB] (76%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/iphone-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Back_cameras_2_Back_plastic_0.geometry} material={materials['Back_plastic.001']} position={[0, 0, -0.049]} scale={0.01} />
      <mesh geometry={nodes.Body_clean_2_Body_metall_roughness_0.geometry} material={materials.PaletteMaterial002} position={[0, 0, -0.102]} scale={0.01} />
      <mesh geometry={nodes.Screen_new_clean_2_Screen_black_camera_0.geometry} material={materials['Screen_black_camera.001']} position={[0, 0, 0.047]} scale={0.01} />
      <mesh geometry={nodes.Screen_new_clean_2_Screen_0.geometry} material={materials['Screen.001']} position={[0, 0, 0.047]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/iphone-transformed.glb')
