/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sci-fi-screen.glb --transform --precision 1 --draco --resolution 256 --simplify true --weld 0.0005 --ratio 0.05 
Files: sci-fi-screen.glb [391.01KB] > /Users/tianyuanbi/Downloads/3D Tim/public/assets/sci-fi-screen-transformed.glb [36.66KB] (91%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/sci-fi-screen-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" scale={0}>
          <group name="pCube12" position={[0, -1, 0]}>
            <mesh name="pCube12_TV_MTL_0" geometry={nodes.pCube12_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube13" position={[0, -1, 0]}>
            <mesh name="pCube13_TV_MTL_0" geometry={nodes.pCube13_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube14" position={[0, -1, 0]}>
            <mesh name="pCube14_TV_MTL_0" geometry={nodes.pCube14_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube15" position={[0, -1, 0]}>
            <mesh name="pCube15_TV_MTL_0" geometry={nodes.pCube15_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube16" position={[0, -1, 0]} scale={[1, 0.3, 1]}>
            <mesh name="pCube16_TV_MTL_0" geometry={nodes.pCube16_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube17" position={[0, -1, 0]} scale={[1, 0.3, 1]}>
            <mesh name="pCube17_TV_MTL_0" geometry={nodes.pCube17_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
          <group name="pCube18" position={[0, -1, 0]} scale={[1, 0.3, 1]}>
            <mesh name="pCube18_TV_MTL_0" geometry={nodes.pCube18_TV_MTL_0.geometry} material={materials.TV_MTL} />
          </group>
        </group>
        <mesh name="BG_BG_MTL_0" geometry={nodes.BG_BG_MTL_0.geometry} material={materials.BG_MTL} scale={0} />
        <mesh name="pCube19_monter_MTL_0" geometry={nodes.pCube19_monter_MTL_0.geometry} material={materials.monter_MTL} position={[-0.1, 0.1, 0]} scale={0} />
        <mesh name="pCube1_TV_MTL_0" geometry={nodes.pCube1_TV_MTL_0.geometry} material={materials.TV_MTL} position={[0, 0.1, 0]} scale={[0.2, 0.1, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sci-fi-screen-transformed.glb')
